export const routes = {
  homePage: "/",
  login: "/login",
  news: "/news",
  newsDetail: "/news-detail",
  classify: "/classify",
  regulation: "/regulation",
  product: "/product",
  sell: '/sell',
  adminproduct: "/admin-product",
  adminorder: "/admin-order",
  adminstatistic: "admin-statistic",
  adminuser: "admin-user",
  cart: "/cart",
  profile: "/profile",
};
